Fix ssl package conflict
Updating to stable postgres 9.5 fixes:

```
ERROR: unsatisfiable constraints:
  openssl-dev-1.0.2n-r0:
    conflicts:
               libressl-dev-2.6.3-r0[pc:libcrypto=1.0.2n]
               libressl-dev-2.6.3-r0[pc:libssl=1.0.2n]
               libressl-dev-2.6.3-r0[pc:openssl=1.0.2n]
    satisfies: .ruby-builddeps-0[openssl-dev]
               .ruby-rundeps-0[openssl-dev]
  postgresql-client-10.2-r0:
    breaks: world[postgresql-client=9.5.7-r0]
  libressl-dev-2.6.3-r0:
    conflicts:
               openssl-dev-1.0.2n-r0[pc:libcrypto=2.6.3]
               openssl-dev-1.0.2n-r0[pc:libssl=2.6.3]
               openssl-dev-1.0.2n-r0[pc:openssl=2.6.3]
    satisfies:
               postgresql-dev-10.2-r0[libressl-dev]
  postgresql-dev-10.2-r0:
    breaks: world[postgresql-dev=9.5.7-r0]
```